services:
  app:
    image: ghcr.io/yousefalfoqaha/nibras:latest
    expose:
      - "8080"
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - OPENAI_API_KEY
    restart: always

  db:
    image: pgvector/pgvector:pg16-trixie
    environment:
      POSTGRES_DB: ${DB_NAME:-chatbot}
      POSTGRES_USER: ${DB_USER:-chatbot}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-chatbot}
    volumes:
      - ./app_data:/var/lib/postgresql/data
    restart: always

  caddy:
    image: caddy:2
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    command: >
      caddy reverse-proxy --from yourdomain.edu --to app:8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

volumes:
  caddy_data:
  caddy_config:
