services:
  app:
    build: .
    # image: ghcr.io/yousefalfoqaha/gju-chatbot
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - OPENAI_API_KEY
    restart: always

  db:
    image: pgvector/pgvector:pg16-trixie
    environment:
      POSTGRES_DB: ${DB_NAME:-chatbot}
      POSTGRES_USER: ${DB_USER:-chatbot}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-chatbot}
    volumes:
      - ./app_data:/var/lib/postgresql/data
    restart: always
