services:
  client:
    image: node:24-alpine
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev --host"
    container_name: gju-chatbot-client
    working_dir: /app
    volumes:
      - ../client:/app
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development
      VITE_PROXY_TARGET: http://api:8080

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: gju-chatbot-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JINA_API_KEY: ${JINA_API_KEY}
      OCR_BASE_URL: http://ocr:8000
    volumes:
      - ../api:/app
    working_dir: /app
    command: mvn spring-boot:run
    depends_on:
      - db

  ocr:
    build:
      context: ../ocr
      dockerfile: Dockerfile
    container_name: gju-chatbot-ocr
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    volumes:
      - ../ocr:/app
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: gju-chatbot-db
    environment:
      POSTGRES_DB: gju
      POSTGRES_USER: gju
      POSTGRES_PASSWORD: gju
    # command: psql -U gju
    volumes:
      - ./dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
