services:
  client:
    build:
      context: ../client
      dockerfile: dev.Dockerfile
    command: pnpm dev --host
    working_dir: /app
    volumes:
      - ../client:/app
      - ../client/node_modules:/app/node_modules
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development
      VITE_PROXY_TARGET: http://api:8080
    depends_on:
      - api

  api:
    build:
      context: ../api
      dockerfile: dev.Dockerfile
    container_name: gju-chatbot
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: ./mvnw spring-boot:run
    working_dir: /app
    volumes:
      - ../api/src:/app/src
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: gju-chatbot-db
    environment:
      POSTGRES_DB: gju
      POSTGRES_USER: gju
      POSTGRES_PASSWORD: gju
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
